import React, { useState } from 'react';
import { ShieldCheck, FileText, Lock, X, Printer, CheckCircle2 } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export default function LegalModal({ isOpen, onClose, initialTab = 'terms' }) {
  const { isRomanUrdu } = useLanguage();
  const [activeTab, setActiveTab] = useState(initialTab);

  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-container legal-modal glass-panel slide-in"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
      >
        <div className="modal-header">
          <div className="modal-title-with-icon">
            <div className="modal-icon-badge icon-badge-cyan">
              <ShieldCheck size={22} className="text-cyan" />
            </div>
            <div>
              <h3>{isRomanUrdu ? 'Qanooni Maloomat aur Policies' : 'Legal Agreements & Policies'}</h3>
              <span className="text-muted text-xs">
                {isRomanUrdu
                  ? 'Falcon Honda Motors — Qanooni Rahnumai aur Privacy'
                  : 'AutoSuite ERP & Dealership Operational Standards'}
              </span>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="btn btn-outline btn-sm no-print" onClick={() => window.print()}>
              <Printer size={14} /> {isRomanUrdu ? 'Print' : 'Print'}
            </button>
            <button className="modal-close-btn" onClick={onClose} aria-label="Close">
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="legal-tabs-bar no-print">
          <button
            className={`legal-tab-btn ${activeTab === 'terms' ? 'active' : ''}`}
            onClick={() => setActiveTab('terms')}
          >
            <FileText size={15} />
            {isRomanUrdu ? 'Terms & Conditions' : 'Terms of Service'}
          </button>
          <button
            className={`legal-tab-btn ${activeTab === 'privacy' ? 'active' : ''}`}
            onClick={() => setActiveTab('privacy')}
          >
            <Lock size={15} />
            {isRomanUrdu ? 'Privacy Policy' : 'Privacy & PII Policy'}
          </button>
          <button
            className={`legal-tab-btn ${activeTab === 'warranty' ? 'active' : ''}`}
            onClick={() => setActiveTab('warranty')}
          >
            <ShieldCheck size={15} />
            {isRomanUrdu ? 'Warranty & Gate Pass' : 'Warranty & Delivery Policy'}
          </button>
        </div>

        <div className="modal-body legal-content-body">
          {activeTab === 'terms' && (
            <div className="legal-section">
              <h4>1. Dealership ERP & Sales Terms of Service</h4>
              <p className="text-xs text-muted mb-3">Effective Date: January 1, 2026 | Document ID: AST-TOS-2026-v2</p>

              <div className="legal-text-block">
                <h5>1.1 Vehicle Ownership & Title Reservation</h5>
                <p>
                  Until the total sales price, including any applicable registration levies, documented surcharges, and financing installment amounts, has been liquidated in full, Falcon Honda Motors retains legal title and ownership rights over any vehicle, chassis, or associated spare inventory.
                </p>

                <h5>1.2 Installment Covenants & Repossession Clause</h5>
                <p>
                  Any installment schedule issued through the AutoSuite ERP platform constitutes a legally binding promissory undertaking under the Negotiable Instruments Act and Contract Act. A grace window of 10 calendar days applies beyond due dates, following which default penalties accrue. In the event of default exceeding 60 days, the dealership reserves statutory rights to recall the vehicle.
                </p>

                <h5>1.3 Invoicing & Electronic Audit Trail</h5>
                <p>
                  Invoices generated by this ERP system bearing official invoice numbering (e.g., INV-YYYY-XXXX) represent definitive proof of transaction. Tampering, unauthorized deletion, or alteration of invoices is strictly prohibited and logged under our immutable 90-day technical audit logging infrastructure.
                </p>

                <h5>1.4 Jurisdiction & Arbitration</h5>
                <p>
                  All commercial agreements, booking receipts, and dealer wholesale contracts shall be governed in accordance with local commercial dealership law and judicial courts of Pakistan.
                </p>
              </div>
            </div>
          )}

          {activeTab === 'privacy' && (
            <div className="legal-section">
              <h4>2. Customer Privacy & CNIC Data Handling Policy</h4>
              <p className="text-xs text-muted mb-3">Compliance: Data Protection Standard & Excise Department Integration</p>

              <div className="legal-text-block">
                <h5>2.1 Collection of Personal Identifiable Information (PII)</h5>
                <p>
                  To facilitate motorcycle registration, chassis verification, excise allotment letters, and warranty claims, AutoSuite ERP processes customer names, mobile telephone numbers, National Computerized Identity Card (CNIC) numbers, residential addresses, and sales transaction metadata.
                </p>

                <h5>2.2 Mandatory Excise & OEM Data Transfer</h5>
                <p>
                  Customer records are securely transmitted solely to official regulatory bodies: (a) The Provincial Excise, Taxation & Narcotics Control Department for vehicular road registration; and (b) Atlas Honda OEM manufacturing verification gateways for vehicle warranty activation. No customer PII is rented, commercialized, or sold to third-party telemarketers.
                </p>

                <h5>2.3 90-Day Retention & Access Log Auditing</h5>
                <p>
                  In accordance with regulatory dealership standards, all administrative access, customer lookup queries, payment transactions, and record modifications are logged with client IP addresses and user timestamps, maintained for a mandatory minimum retention window of at least ninety (90) days in compliance with ISO/dealership audit protocols.
                </p>

                <h5>2.4 Soft Deletion & Right to Rectification</h5>
                <p>
                  Customers and staff may request correction of erroneous data. In accordance with enterprise integrity standards, deleted records are soft-deleted from active views while audit references remain preserved for fiscal audit compliance.
                </p>
              </div>
            </div>
          )}

          {activeTab === 'warranty' && (
            <div className="legal-section">
              <h4>3. Motorcycle Warranty, Gate Pass & Service Guidelines</h4>
              <p className="text-xs text-muted mb-3">Atlas Honda OEM Authorized Dealership Operations</p>

              <div className="legal-text-block">
                <h5>3.1 Official Delivery Letter & Gate Pass Protocols</h5>
                <p>
                  No motorcycle shall exit the showroom floor or bonded storage yard without an authorized AutoSuite ERP Delivery Letter and Gate Pass containing verified matching Engine Number, Chassis Number, and Sales Officer electronic signature.
                </p>

                <h5>3.2 Manufacturer Warranty Coverage</h5>
                <p>
                  Brand new motorcycles carry manufacturer standard warranty coverage for 20,000 kilometers or 24 months (whichever transpires earlier), conditioned upon adherence to authorized scheduled maintenance coupons using genuine OEM 4T engine oils and Atlas Honda certified spare parts.
                </p>

                <h5>3.3 Certified Pre-Owned (Used) Vehicle Disclaimer</h5>
                <p>
                  Used motorcycles are certified according to condition grading (Grade A, B, or C). Pre-owned vehicle sales are final upon customer physical inspection and execution of the Book Transfer and Allotment request form.
                </p>

                <h5>3.4 Registration Book & Smart Card Pickup</h5>
                <p>
                  Customers will receive an automated SMS/System notification when vehicle registration smart cards and excise return books are stamped and ready for counter collection.
                </p>
              </div>
            </div>
          )}
        </div>

        <div className="modal-footer">
          <div className="flex items-center gap-2 text-xs text-muted">
            <CheckCircle2 size={15} className="text-emerald" />
            <span>{isRomanUrdu ? 'AutoSuite Dealership ERP se tasdeeq shuda' : 'Verified compliance document — AutoSuite ERP'}</span>
          </div>
          <button type="button" className="btn btn-primary" onClick={onClose}>
            {isRomanUrdu ? 'Samajh Aa Gaya / Band Karein' : 'Close & Return'}
          </button>
        </div>
      </div>
    </div>
  );
}
